<a href="https://colab.research.google.com/github/AdamN5/CampusDatasetProject/blob/main/Campus_Dataset_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Campus Dataset Project text**
Adam Nafea 2026

## Data Preparation
This section loads the campus dataset and prepares it for analysis.

In [62]:
import pandas as pd

### Load the Dataset

Raw data from the CSV

In [63]:
df = pd.read_csv(
    '/content/drive/MyDrive/Colab Notebooks/CampusWalkDataset_TemplateIDs(Sheet1).csv',
    skiprows = 4
    )

Inspect the dataset structure...

Below shows data tyoes and a sample of data before we start cleaning and encoding.

In [64]:
print("Column names")
print(df.dtypes)

print("\nSample rows\n")
print(df.head())

Column names
recorder_id                               object
date                                      object
location                                  object
weather                                   object
temperature_c                             object
sound level                               object
foot_traffic                              object
primary_sound_type_urban                  object
other_sound_type_urban                    object
primary_sound_type_nature                 object
other_sound_type_nature                   object
insects_count                            float64
birds_count                              float64
trees_presence                            object
native_or_wild_plant_presence             object
ornnamental_or_planted_plant_presence     object
moss_or_lichen_presence                   object
wellbeing_rating                          object
ease_rating                               object
stress_rating                             object
nature_connection_experience_rating       object
most_notable_nature_element               object
other_notes                               object
Unnamed: 23                              float64
Unnamed: 24                              float64
Unnamed: 25                              float64
Unnamed: 26                              float64
dtype: object

Sample rows

  recorder_id       date                        location        weather  \
0     R26_001  9/22/2026                L01 MainEntrance  Partly cloudy
1     R26_001  9/22/2026                L02 LibraryGreen          Sunny
2     R26_001  9/22/2026   L06 HedgingBehindSportsCentre  Partly cloudy
3     R26_001  9/22/2026  L08 AccessRoadNearSportsCentre  Partly cloudy
4     R26_001  9/22/2026   L06 HedgingBehindSportsCentre          Sunny

  temperature_c sound level foot_traffic primary_sound_type_urban  \
0            16       Quiet          Low             Human voices
1            16    Moderate          Low                  Traffic
2            16       Quiet          Low             Construction
3            16    Moderate          Low             Human voices
4            16    Moderate          Low                  Traffic

  other_sound_type_urban primary_sound_type_nature other_sound_type_nature  \
0                Traffic                      Wind                   Trees
1           Human voices                      Wind                   Trees
2                Traffic                      Wind             Other birds
3           Human voices                      Wind             Other birds
4                  Other                      Wind                   Trees

   insects_count  birds_count trees_presence native_or_wild_plant_presence  \
0            0.0          1.0           Many                         Some
1            0.0          2.0           Many                           NaN
2           10.0         20.0           Many                           NaN
3            0.0          2.0     One or two                         Some
4            0.0          0.0     One or two                           NaN

  ornnamental_or_planted_plant_presence moss_or_lichen_presence  \
0                                 Some                     Some
1                                 Some                      NaN
2                                  Many                    Some
3                                   NaN                    Some
4                                 Some                      NaN

     wellbeing_rating ease_rating stress_rating  \
0  Positive wellbeing     Neutral     Stressful
1  Positive wellbeing     Neutral       Neutral
2  Positive wellbeing        Easy   Mostly calm
3  Positive wellbeing     Neutral       Neutral
4  Positive wellbeing        Easy   Mostly calm

  nature_connection_experience_rating most_notable_nature_element other_notes  \
0                      Less connected            Plants and trees         NaN
1             A little more connected            Sunrays on grass         NaN
2                           No change                  Very quiet         NaN
3                 Much more connected                 Harsh wind          NaN
4                      Less connected               Crowded area          NaN

   Unnamed: 23  Unnamed: 24  Unnamed: 25  Unnamed: 26
0          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN

Below is to set the limits of what will be shown when we display the data frame, in this case we dont want any cut offs we want to show every row and column in the table so we can clean them easier later.

In [65]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)


pd.set_option('display.max_colwidth', None)

display(df)

    recorder_id        date                        location        weather  \
0       R26_001   9/22/2026                L01 MainEntrance  Partly cloudy
1       R26_001   9/22/2026                L02 LibraryGreen          Sunny
2       R26_001   9/22/2026   L06 HedgingBehindSportsCentre  Partly cloudy
3       R26_001   9/22/2026  L08 AccessRoadNearSportsCentre  Partly cloudy
4       R26_001   9/22/2026   L06 HedgingBehindSportsCentre          Sunny
5       R26_002   9/22/2026                L01 MainEntrance          Sunny
6       R26_002   9/22/2026               L04 PathFrontiHub          Windy
7       R26_002   9/22/2026      L05 GreenFrontSportsCentre          Sunny
8       R26_002   9/22/2026   L06 HedgingBehindSportsCentre         Cloudy
9       R26_002   9/22/2026     L07 CarParkNearSportsCentre          Sunny
10      R26_003   9/22/2026                L01 MainEntrance          Sunny
11      R26_003   9/22/2026               L04 PathFrontiHub          Sunny
12      R26_003   9/22/2026      L05 GreenFrontSportsCentre          Sunny
13      R26_003   9/22/2026   L06 HedgingBehindSportsCentre         Cloudy
14      R26_003   9/22/2026     L07 CarParkNearSportsCentre          Sunny
15      R26_004   9/22/2026               L04 PathFrontiHub          Sunny
16      R26_004   9/22/2026   L06 HedgingBehindSportsCentre          Sunny
17      R26_004   9/22/2026                L01 MainEntrance          Sunny
18      R26_004   9/22/2026      L05 GreenFrontSportsCentre          Sunny
19      R26_004   9/22/2026                L02 LibraryGreen          Sunny
20      R26_005   9/22/2026                L01 MainEntrance          Sunny
21      R26_005   9/22/2026                L02 LibraryGreen          Sunny
22      R26_005   9/22/2026               L04 PathFrontiHub          Sunny
23      R26_005   9/22/2026      L05 GreenFrontSportsCentre          Sunny
24      R26_005   9/22/2026   L06 HedgingBehindSportsCentre          Sunny
25      R26_006   9/22/2026                L01 MainEntrance  Partly cloudy
26      R26_006   9/22/2026                L02 LibraryGreen  Partly cloudy
27      R26_006   9/22/2026   L06 HedgingBehindSportsCentre  Partly cloudy
28      R26_006   9/22/2026     L07 CarParkNearSportsCentre          Sunny
29      R26_006   9/22/2026  L08 AccessRoadNearSportsCentre  Partly cloudy
30      R26_007   9/22/2026                L01 MainEntrance  Partly cloudy
31      R26_007   9/22/2026           L03 LowerSidePathiHub         Cloudy
32      R26_007   9/22/2026               L04 PathFrontiHub          Sunny
33      R26_007   9/22/2026   L06 HedgingBehindSportsCentre         Cloudy
34      R26_007   9/22/2026  L08 AccessRoadNearSportsCentre  Partly cloudy
35      R26_008  22/09/2026                L01 MainEntrance  Partly cloudy
36      R26_008  22/09/2026           L03 LowerSidePathiHub  Partly cloudy
37      R26_008  22/09/2026  L08 AccessRoadNearSportsCentre  Partly cloudy
38      R26_008  22/09/2026   L06 HedgingBehindSportsCentre  Partly cloudy
39      R26_008  22/09/2026               L04 PathFrontiHub  Partly cloudy
40      R26_009   9/22/2026                L01 MainEntrance          Sunny
41      R26_009   9/22/2026                L02 LibraryGreen          Sunny
42      R26_009   9/22/2026               L04 PathFrontiHub          Sunny
43      R26_009   9/22/2026      L05 GreenFrontSportsCentre          Sunny
44      R26_009   9/22/2026   L06 HedgingBehindSportsCentre          Sunny
45      R26_010   9/22/2026                L01 MainEntrance  Partly cloudy
46      R26_010   9/22/2026                L02 LibraryGreen  Partly cloudy
47      R26_010   9/22/2026               L04 PathFrontiHub  Partly cloudy
48      R26_010   9/22/2026      L05 GreenFrontSportsCentre  Partly cloudy
49      R26_010   9/22/2026   L06 HedgingBehindSportsCentre  Partly cloudy
50      R26_011   9/22/2026                L01 MainEntrance  Partly cloudy
51      R26_011   9/22/2026                L02 LibraryGreen  Partly cloudy
52      R26_011   9/22/2026           L03 LowerSidePathiHub  Partly cloudy
53      R26_011   9/22/2026      L05 GreenFrontSportsCentre  Partly cloudy
54      R26_011   9/22/2026   L06 HedgingBehindSportsCentre  Partly cloudy
55      R26_012   9/22/2026      L05 GreenFrontSportsCentre          Sunny
56      R26_012   9/22/2026                L02 LibraryGreen          Sunny
57      R26_012   9/22/2026   L06 HedgingBehindSportsCentre         Cloudy
58      R26_012   9/22/2026                L01 MainEntrance          Sunny
59      R26_013   9/22/2026                L01 MainEntrance          Sunny
60      R26_013   9/22/2026                L02 LibraryGreen          Sunny
61      R26_013   9/22/2026               L04 PathFrontiHub          Sunny
62      R26_013   9/22/2026      L05 GreenFrontSportsCentre          Sunny
63      R26_013   9/22/2026   L06 HedgingBehindSportsCentre          Sunny
64      R26_014   9/22/2026               L04 PathFrontiHub          Sunny
65      R26_014   9/22/2026      L05 GreenFrontSportsCentre          Sunny
66      R26_014         NaN                             NaN            NaN
67      R26_014         NaN                             NaN            NaN
68      R26_014         NaN                             NaN            NaN
69      R26_015   9/23/2026                L02 LibraryGreen          Sunny
70      R26_015   9/23/2026               L04 PathFrontiHub          Sunny
71      R26_015   9/23/2026      L05 GreenFrontSportsCentre          Sunny
72      R26_015   9/23/2026   L06 HedgingBehindSportsCentre          Sunny
73      R26_015   9/23/2026     L07 CarParkNearSportsCentre          Sunny
74      R26_016   9/23/2026                L02 LibraryGreen          Sunny
75      R26_016   9/23/2026               L04 PathFrontiHub          Sunny
76      R26_016   9/23/2026      L05 GreenFrontSportsCentre          Sunny
77      R26_016   9/23/2026   L06 HedgingBehindSportsCentre          Sunny
78      R26_016   9/23/2026     L07 CarParkNearSportsCentre          Sunny
79      R26_017   9/23/2026                L01 MainEntrance  Partly cloudy
80      R26_017   9/23/2026                L02 LibraryGreen  Partly cloudy
81      R26_017   9/23/2026     L07 CarParkNearSportsCentre  Partly cloudy
82      R26_017   9/23/2026   L06 HedgingBehindSportsCentre  Partly cloudy
83      R26_017   9/23/2026               L04 PathFrontiHub  Partly cloudy
84      R26_018   9/23/2026      L05 GreenFrontSportsCentre  Partly cloudy
85      R26_018   9/23/2026   L06 HedgingBehindSportsCentre          Sunny
86      R26_018   9/23/2026     L07 CarParkNearSportsCentre  Partly cloudy
87      R26_018   9/23/2026                L02 LibraryGreen  Partly cloudy
88      R26_018   9/23/2026               L04 PathFrontiHub  Partly cloudy
89      R26_019   9/24/2026               L04 PathFrontiHub          Sunny
90      R26_019   9/25/2026           L03 LowerSidePathiHub          Sunny
91      R26_019   9/26/2026      L05 GreenFrontSportsCentre          Sunny
92      R26_019   9/27/2026   L06 HedgingBehindSportsCentre          Sunny
93      R26_019   9/28/2026     L07 CarParkNearSportsCentre          Sunny
94      R26_020   9/23/2026      L05 GreenFrontSportsCentre          sunny
95      R26_021   9/24/2026           L03 LowerSidePathiHub          sunny
96      R26_022   9/25/2026   L06 HedgingBehindSportsCentre          sunny
97      R26_023   9/26/2026     L07 CarParkNearSportsCentre          sunny
98      R26_024   9/27/2026                L01 MainEntrance          sunny
99      R26_021   9/23/2026                L01 MainEntrance          Sunny
100     R26_021   9/23/2026           L03 LowerSidePathiHub          Sunny
101     R26_021   9/23/2026      L05 GreenFrontSportsCentre          Sunny
102     R26_021   9/23/2026   L06 HedgingBehindSportsCentre          Sunny
103     R26_021   9/23/2026     L07 CarParkNearSportsCentre          Sunny
104     R26_022   9/23/2026                L01 MainEntrance          Sunny
105     R26_022   9/23/2026           L03 LowerSidePathiHub          Sunny
106     R26_022   9/23/2026   L06 HedgingBehindSportsCentre          Sunny
107     R26_022   9/23/2026     L07 CarParkNearSportsCentre          Sunny
108     R26_022   9/23/2026  L08 AccessRoadNearSportsCentre          Sunny
109     R26_023  23/09/2026                L01 MainEntrance         Cloudy
110     R26_023  23/09/2026           L03 LowerSidePathiHub          Sunny
111     R26_023  23/09/2026   L06 HedgingBehindSportsCentre         Cloudy
112     R26_023  23/09/2026     L07 CarParkNearSportsCentre          Sunny
113     R26_023  23/09/2026  L08 AccessRoadNearSportsCentre          Sunny
114     R26_024   9/23/2026      L05 GreenFrontSportsCentre          Windy
115     R26_024   9/23/2026   L06 HedgingBehindSportsCentre          Sunny
116     R26_024   9/23/2026     L07 CarParkNearSportsCentre          Sunny
117     R26_024   9/23/2026                L01 MainEntrance  Partly cloudy
118     R26_024   9/23/2026               L04 PathFrontiHub          Sunny
119     R26_025   9/23/2026                L01 MainEntrance          Sunny
120     R26_025   9/23/2026     L07 CarParkNearSportsCentre          Sunny
121     R26_025   9/23/2026   L06 HedgingBehindSportsCentre          Sunny
122     R26_025   9/23/2026      L05 GreenFrontSportsCentre          Sunny
123     R26_025   9/23/2026               L04 PathFrontiHub          Sunny
124     R26_026  23/09/2026                L01 MainEntrance  Partly cloudy
125     R26_026  23/09/2026                L02 LibraryGreen          Sunny
126     R26_026  23/09/2026           L03 LowerSidePathiHub          Sunny
127     R26_026  23/09/2026   L06 HedgingBehindSportsCentre          Sunny
128     R26_026  23/09/2026  L08 AccessRoadNearSportsCentre          Sunny
129     R26_027  23/09/2026                L01 MainEntrance  Partly cloudy
130     R26_027  23/09/2026     L07 CarParkNearSportsCentre          Sunny
131     R26_027  23/09/2026   L06 HedgingBehindSportsCentre          Sunny
132     R26_027  23/09/2026      L05 GreenFrontSportsCentre          Windy
133     R26_027  23/09/2026               L04 PathFrontiHub          Windy
134     R26_028         NaN                             NaN            NaN
135     R26_028         NaN                             NaN            NaN
136     R26_028         NaN                             NaN            NaN
137     R26_028         NaN                             NaN            NaN
138     R26_028         NaN                             NaN            NaN
139     R26_029         NaN                             NaN            NaN
140     R26_029         NaN                             NaN            NaN
141     R26_029         NaN                             NaN            NaN
142     R26_029         NaN                             NaN            NaN
143     R26_029         NaN                             NaN            NaN
144     R26_030         NaN                             NaN            NaN
145     R26_030         NaN                             NaN            NaN
146     R26_030         NaN                             NaN            NaN
147     R26_030         NaN                             NaN            NaN
148     R26_030         NaN                             NaN            NaN
149     R26_031         NaN                             NaN            NaN
150     R26_031         NaN                             NaN            NaN
151     R26_031         NaN                             NaN            NaN
152     R26_031         NaN                             NaN            NaN
153     R26_031         NaN                             NaN            NaN
154     R26_032         NaN                             NaN            NaN
155     R26_032         NaN                             NaN            NaN
156     R26_032         NaN                             NaN            NaN
157     R26_032         NaN                             NaN            NaN
158     R26_032         NaN                             NaN            NaN
159     R26_033         NaN                             NaN            NaN
160     R26_033         NaN                             NaN            NaN
161     R26_033         NaN                             NaN            NaN
162     R26_033         NaN                             NaN            NaN
163     R26_033         NaN                             NaN            NaN
164     R26_034         NaN                             NaN            NaN
165     R26_034         NaN                             NaN            NaN
166     R26_034         NaN                             NaN            NaN
167     R26_034         NaN                             NaN            NaN
168     R26_034         NaN                             NaN            NaN
169     R26_035         NaN                             NaN            NaN
170     R26_035         NaN                             NaN            NaN
171     R26_035         NaN                             NaN            NaN
172     R26_035         NaN                             NaN            NaN
173     R26_035         NaN                             NaN            NaN
174     R26_036         NaN                             NaN            NaN
175     R26_036         NaN                             NaN            NaN
176     R26_036         NaN                             NaN            NaN
177     R26_036         NaN                             NaN            NaN
178     R26_036         NaN                             NaN            NaN
179     R26_037         NaN                             NaN            NaN
180     R26_037         NaN                             NaN            NaN
181     R26_037         NaN                             NaN            NaN
182     R26_037         NaN                             NaN            NaN
183     R26_037         NaN                             NaN            NaN
184     R26_038         NaN                             NaN            NaN
185     R26_038         NaN                             NaN            NaN
186     R26_038         NaN                             NaN            NaN
187     R26_038         NaN                             NaN            NaN
188     R26_038         NaN                             NaN            NaN
189     R26_039         NaN                             NaN            NaN
190     R26_039         NaN                             NaN            NaN
191     R26_039         NaN                             NaN            NaN
192     R26_039         NaN                             NaN            NaN
193     R26_039         NaN                             NaN            NaN
194     R26_040         NaN                             NaN            NaN
195     R26_040         NaN                             NaN            NaN
196     R26_040         NaN                             NaN            NaN
197     R26_040         NaN                             NaN            NaN
198     R26_040         NaN                             NaN            NaN
199         NaN         NaN                             NaN            NaN
200         NaN         NaN                             NaN            NaN
201         NaN         NaN                             NaN            NaN
202         NaN         NaN                             NaN            NaN
203         NaN         NaN                             NaN            NaN
204         NaN         NaN                             NaN            NaN
205         NaN         NaN                             NaN            NaN
206         NaN         NaN                             NaN            NaN
207         NaN         NaN                             NaN            NaN
208         NaN         NaN                             NaN            NaN
209         NaN         NaN                             NaN            NaN
210         NaN         NaN                             NaN            NaN
211         NaN         NaN                             NaN            NaN
212         NaN         NaN                             NaN            NaN
213         NaN         NaN                             NaN            NaN
214         NaN         NaN                             NaN            NaN
215         NaN         NaN                             NaN            NaN
216         NaN         NaN                             NaN            NaN
217         NaN         NaN                             NaN            NaN
218         NaN         NaN                             NaN            NaN
219         NaN         NaN                             NaN            NaN
220         NaN         NaN                             NaN            NaN
221         NaN         NaN                             NaN            NaN
222         NaN         NaN                             NaN            NaN
223         NaN         NaN                             NaN            NaN
224         NaN         NaN                             NaN            NaN
225         NaN         NaN                             NaN            NaN
226         NaN         NaN                             NaN            NaN
227         NaN         NaN                             NaN            NaN
228         NaN         NaN                             NaN            NaN
229         NaN         NaN                             NaN            NaN
230         NaN         NaN                             NaN            NaN
231         NaN         NaN                             NaN            NaN
232         NaN         NaN                             NaN            NaN
233         NaN         NaN                             NaN            NaN
234         NaN         NaN                             NaN            NaN
235         NaN         NaN                             NaN            NaN
236         NaN         NaN                             NaN            NaN
237         NaN         NaN                             NaN            NaN
238         NaN         NaN                             NaN            NaN
239         NaN         NaN                             NaN            NaN
240         NaN         NaN                             NaN            NaN
241         NaN         NaN                             NaN            NaN
242         NaN         NaN                             NaN            NaN
243         NaN         NaN                             NaN            NaN
244         NaN         NaN                             NaN            NaN
245         NaN         NaN                             NaN            NaN
246         NaN         NaN                             NaN            NaN
247         NaN         NaN                             NaN            NaN
248         NaN         NaN                             NaN            NaN
249         NaN         NaN                             NaN            NaN
250         NaN         NaN                             NaN            NaN
251         NaN         NaN                             NaN            NaN
252         NaN         NaN                             NaN            NaN
253         NaN         NaN                             NaN            NaN
254         NaN         NaN                             NaN            NaN
255         NaN         NaN                             NaN            NaN
256         NaN         NaN                             NaN            NaN
257         NaN         NaN                             NaN            NaN
258         NaN         NaN                             NaN            NaN
259         NaN         NaN                             NaN            NaN
260         NaN         NaN                             NaN            NaN
261         NaN         NaN                             NaN            NaN
262         NaN         NaN                             NaN            NaN
263         NaN         NaN                             NaN            NaN
264         NaN         NaN                             NaN            NaN

### Cleaning the Data
Initial clean of data getting rid of unused rows or columns

I noticed there were some blank rows in the middle and end of the sheet, also there were unamed columns that were not being used.

Since the original excel sheet had extra IDs in the ID column but no additional data I decided to use the the location as the data would be more or less useless without the location.

I got rid of the unamed columns by just dropping columns with Unamed.

In [66]:
df = df.dropna(subset=["location"])

df = df.drop(columns=df.columns[df.columns.str.contains('Unnamed')])

display(df)

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,other_sound_type_nature,insects_count,birds_count,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element,other_notes
0,R26_001,9/22/2026,L01 MainEntrance,Partly cloudy,16,Quiet,Low,Human voices,Traffic,Wind,Trees,0.0,1.0,Many,Some,Some,Some,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees,NaN
1,R26_001,9/22/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,2.0,Many,NaN,Some,NaN,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass,NaN
2,R26_001,9/22/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Wind,Other birds,10.0,20.0,Many,NaN,Many,Some,Positive wellbeing,Easy,Mostly calm,No change,Very quiet,NaN
3,R26_001,9/22/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Human voices,Wind,Other birds,0.0,2.0,One or two,Some,NaN,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind,NaN
4,R26_001,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,16,Moderate,Low,Traffic,Other,Wind,Trees,0.0,0.0,One or two,NaN,Some,NaN,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area,NaN
5,R26_002,9/22/2026,L01 MainEntrance,Sunny,17,Moderate,Low,Traffic,Human voices,Other birds,Insects,2.0,4.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush
6,R26_002,9/22/2026,L04 PathFrontiHub,Windy,17,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Neutral,Neutral,Very calm,No change,plants and trees,NaN
7,R26_002,9/22/2026,L05 GreenFrontSportsCentre,Sunny,19,Moderate,Low,Traffic,Service machinery,Wind,Other,7.0,0.0,Many,Many,Many,Many,Positive wellbeing,Vey easy,Mostly calm,Much more connected,wild plants,NaN
8,R26_002,9/22/2026,L06 HedgingBehindSportsCentre,Cloudy,16,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Very calm,Less connected,shaded area,NaN
9,R26_002,9/22/2026,L07 CarParkNearSportsCentre,Sunny,18,Quiet,Low,Service machinery,Traffic,Other birds,Trees,6.0,2.0,Many,Many,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,insects,NaN
10,R26_003,9/22/2026,L01 MainEntrance,Sunny,18,Moderate,Low,Traffic,Human voices,Other birds,Wind,1.0,4.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush
11,R26_003,9/22/2026,L04 PathFrontiHub,Sunny,17,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Easy,Mostly calm,Much more connected,The Plants,NaN
12,R26_003,9/22/2026,L05 GreenFrontSportsCentre,Sunny,18,Moderate,Moderate,Traffic,Service machinery,Wind,Insects,7.0,1.0,Many,Many,Many,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,The Wild Plants,NaN
13,R26_003,9/22/2026,L06 HedgingBehindSportsCentre,Cloudy,16,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,Less connected,Shaded area,NaN
14,R26_003,9/22/2026,L07 CarParkNearSportsCentre,Sunny,18,Quiet,Low,Service machinery,Traffic,Trees,Insects,5.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Insects,NaN
15,R26_004,9/22/2026,L04 PathFrontiHub,Sunny,17,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Plants,NaN
16,R26_004,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,16,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,Less connected,Shaded area,NaN
17,R26_004,9/22/2026,L01 MainEntrance,Sunny,17,Moderate,Low,Traffic,Human voices,Other birds,Wind,1.0,4.0,One or two,Some,Some,Many,Very positive wellbeing,Vey easy,Very calm,Much more connected,Trees,NaN
18,R26_004,9/22/2026,L05 GreenFrontSportsCentre,Sunny,19,Moderate,Low,Traffic,Human voices,Wind,Insects,1.0,0.0,Many,Many,Many,Many,Very positive wellbeing,Vey easy,Very calm,Much more connected,Reddish plants,NaN
19,R26_004,9/22/2026,L02 LibraryGreen,Sunny,18,Quiet,Low,Service machinery,Traffic,Trees,Insects,5.0,2.0,Many,Some,Some,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Insects,NaN
20,R26_005,9/22/2026,L01 MainEntrance,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,1.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,The wind,NaN
21,R26_005,9/22/2026,L02 LibraryGreen,Sunny,16,Quiet,Low,Traffic,Human voices,Trees,Insects,1.0,0.0,Many,Some,Many,NaN,Very positive wellbeing,Vey easy,Very calm,Much more connected,Leaves falling,NaN
22,R26_005,9/22/2026,L04 PathFrontiHub,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Other,0.0,3.0,Many,Some,Some,NaN,Very low wellbeing,Very uneasy,Very stressful,No change,Faint music from car,NaN
23,R26_005,9/22/2026,L05 GreenFrontSportsCentre,Sunny,15,Quiet,Low,Other,Human voices,Trees,Other birds,0.0,2.0,Many,Many,Many,Some,Low wellbeing,Vey easy,Mostly calm,Much more connected,Quiet,NaN
24,R26_005,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,16,Quiet,Low,Construction,Traffic,Seagulls,Other birds,2.0,4.0,Many,Many,Some,Some,Low wellbeing,Slighly uneasy,Mostly calm,No change,Seaguls,NaN
25,R26_006,9/22/2026,L01 MainEntrance,Partly cloudy,16,Moderate,Moderate,Human voices,Traffic,Wind,Other birds,0.0,0.0,Many,NaN,Some,Some,Low wellbeing,Slighly uneasy,Stressful,Less connected,Trees,NaN
26,R26_006,9/22/2026,L02 LibraryGreen,Partly cloudy,16,Moderate,Low,Traffic,Human voices,Other birds,Wind,5.0,2.0,Many,NaN,NaN,NaN,Neutral,Easy,Neutral,A little more connected,Grass,NaN
27,R26_006,9/22/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Other birds,Wind,2.0,12.0,One or two,NaN,Some,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Plants,NaN
28,R26_006,9/22/2026,L07 CarParkNearSportsCentre,Sunny,16,Quiet,Low,Construction,Traffic,Wind,Trees,0.0,1.0,One or two,Some,NaN,Some,Very low wellbeing,Slighly uneasy,Stressful,Less connected,lawn,NaN
29,R26_006,9/22/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Traffic,Other,Wind,Other birds,0.0,0.0,One or two,NaN,Some,Some,Low wellbeing,Neutral,Mostly calm,No change,Tree,Generator
30,R26_007,9/22/2026,L01 MainEntrance,Partly cloudy,17,Moderate,High,Human voices,Traffic,Trees,Other birds,3.0,4.0,Many,Some,Many,Some,Neutral,Slighly uneasy,Stressful,No change,Wind,NaN
31,R26_007,9/22/2026,L03 LowerSidePathiHub,Cloudy,16,Moderate,Low,Traffic,Human voices,Other birds,Insects,3.0,1.0,One or two,Some,NaN,Many,Positive wellbeing,Neutral,Mostly calm,No change,NaN,Trash
32,R26_007,9/22/2026,L04 PathFrontiHub,Sunny,17,Loud,Moderate,Traffic,Human voices,Other birds,Wind,3.0,1.0,One or two,Some,Some,Some,Neutral,Slighly uneasy,Mostly calm,No change,Wind,Ambulance
33,R26_007,9/22/2026,L06 HedgingBehindSportsCentre,Cloudy,15,Quiet,Moderate,Traffic,Construction,Trees,Other birds,31.0,12.0,Many,Some,Many,Many,Positive wellbeing,Easy,Mostly calm,No change,Snails on wall,NaN
34,R26_007,9/22/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Quiet,Low,Traffic,Other,Wind,Other birds,4.0,1.0,One or two,Some,Some,Many,Neutral,Slighly uneasy,Neutral,No change,Tweeting Birds,NaN
35,R26_008,22/09/2026,L01 MainEntrance,Partly cloudy,16,Moderate,Moderate,Human voices,Traffic,Wind,Wind,1.0,3.0,Many,Some,NaN,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Sunny,NaN
36,R26_008,22/09/2026,L03 LowerSidePathiHub,Partly cloudy,16,Moderate,Low,Traffic,Traffic,Trees,Wind,0.0,3.0,Many,Many,NaN,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,Quiet,NaN
37,R26_008,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Quiet,Low,Service machinery,Traffic,Wind,Other birds,3.0,3.0,One or two,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,NaN
38,R26_008,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Human voices,Human voices,Wind,Trees,26.0,13.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,A soft yellow golf ball
39,R26_008,22/09/2026,L04 PathFrontiHub,Partly cloudy,16,Moderate,Moderate,Traffic,Other,Wind,Wind,1.0,3.0,Many,Some,Some,NaN,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,NaN
40,R26_009,9/22/2026,L01 MainEntrance,Sunny,16,Moderate,Moderate,Human voices,Traffic,Trees,Other birds,1.0,3.0,Many,Some,Many,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Barren,People smoking
41,R26_009,9/22/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Trees,1.0,1.0,Many,Many,Some,Many,Very positive wellbeing,Easy,Very calm,Much more connected,Fallen leaves,Bags left outside library wall
42,R26_009,9/22/2026,L04 PathFrontiHub,Sunny,16,Loud,Low,Traffic,Human voices,Wind,Trees,0.0,1.0,Many,Some,Many,Many,Neutral,Slighly uneasy,Stressful,Less connected,More variety in planted shrubs,Loud traffic noise
43,R26_009,9/22/2026,L05 GreenFrontSportsCentre,Sunny,17,Quiet,Low,Traffic,Human voices,Wind,Trees,5.0,0.0,Many,Many,Many,Many,Very positive wellbeing,Easy,Mostly calm,Much more connected,Little annoying bugs,Lots of dumped clothes
44,R26_009,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,15,Quiet,Low,Traffic,Construction,Trees,Seagulls,6.0,1.0,NaN,Some,Some,Many,Neutral,Neutral,Very calm,Much more connected,Lots of bushes,Yellow Golfball
45,R26_010,9/22/2026,L01 MainEntrance,Partly cloudy,17,Moderate,Low,Human voices,Traffic,Wind,Other birds,1.0,0.0,Many,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Smoking people,NaN
46,R26_010,9/22/2026,L02 LibraryGreen,Partly cloudy,17,Loud,Moderate,Traffic,Human voices,Wind,Wind,0.0,2.0,Many,Some,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,More birds,NaN
47,R26_010,9/22/2026,L04 PathFrontiHub,Partly cloudy,17,Loud,Low,Traffic,Human voices,Wind,Insects,1.0,0.0,Many,Some,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Spider,NaN
48,R26_010,9/22/2026,L05 GreenFrontSportsCentre,Partly cloudy,17,Moderate,Low,Traffic,Traffic,Wind,Wind,0.0,0.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Trafic sound,NaN
49,R26_010,9/22/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17,Quiet,Low,Traffic,Traffic,Wind,Wind,0.0,0.0,NaN,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,crab apple,NaN
50,R26_011,9/22/2026,L01 MainEntrance,Partly cloudy,17,Loud,High,Human voices,Traffic,Wind,Other birds,1.0,2.0,Many,Many,NaN,Some,Positive wellbeing,Easy,Very calm,No change,Trees,Smoking
51,R26_011,9/22/2026,L02 LibraryGreen,Partly cloudy,16,Loud,Moderate,Traffic,Human voices,Other birds,Trees,4.0,2.0,Many,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,Less connected,Grass,NaN
52,R26_011,9/22/2026,L03 LowerSidePathiHub,Partly cloudy,17,Quiet,Low,Human voices,Traffic,Seagulls,Wind,0.0,2.0,One or two,Some,Many,Some,Positive wellbeing,Easy,Very calm,No change,Flowerbed,NaN
53,R26_011,9/22/2026,L05 GreenFrontSportsCentre,Partly cloudy,17,Moderate,Low,Traffic,Human voices,Trees,Wind,3.0,1.0,Many,Many,Some,NaN,Positive wellbeing,Easy,Very calm,No change,Wildflower area,pathway
54,R26_011,9/22/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17,Quiet,Low,Other,Human voices,Other birds,Trees,1.0,2.0,Many,Some,Many,NaN,Positive wellbeing,Easy,Very calm,No change,Bush,gunshots
55,R26_012,9/22/2026,L05 GreenFrontSportsCentre,Sunny,18,Moderate,Low,Traffic,Other,Other,Wind,20.0,0.0,Many,Many,NaN,Some,Neutral,Neutral,Neutral,Less connected,some sort of a falcon,NaN
56,R26_012,9/22/2026,L02 LibraryGreen,Sunny,17,Loud,Moderate,Traffic,Human voices,Other birds,Other birds,0.0,10.0,Many,NaN,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Birds, Trees",Construction site
57,R26_012,9/22/2026,L06 HedgingBehindSportsCentre,Cloudy,13,Quiet,Low,Construction,Traffic,Other birds,Trees,10.0,5.0,Many,Some,NaN,NaN,Very positive wellbeing,Vey easy,Very calm,No change,"Trees, bushes",People
58,R26_012,9/22/2026,L01 MainEntrance,Sunny,17,Loud,High,Human voices,Traffic,Other birds,Wind,0.0,5.0,Many,NaN,Some,Many,Very positive wellbeing,Vey easy,Mostly calm,No change,"Trees, birds, wind sound",People smoking
59,R26_013,9/22/2026,L01 MainEntrance,Sunny,16,Moderate,High,Human voices,Traffic,Wind,Trees,0.0,3.0,Many,Some,NaN,NaN,Positive wellbeing,Neutral,Very calm,No change,Leaves,NaN
60,R26_013,9/22/2026,L02 LibraryGreen,Sunny,17,Quiet,Low,Traffic,Human voices,Wind,Trees,1.0,0.0,Many,Many,Some,Many,Positive wellbeing,Vey easy,Very calm,Much more connected,Moss,NaN
61,R26_013,9/22/2026,L04 PathFrontiHub,Sunny,16.5,Moderate,Low,Traffic,Human voices,Wind,Other birds,1.0,1.0,Many,Some,Some,Many,Positive wellbeing,Slighly uneasy,Stressful,Less connected,Wind,NaN
62,R26_013,9/22/2026,L05 GreenFrontSportsCentre,Sunny,18,Quiet,Low,Traffic,Human voices,Wind,Other birds,1.0,2.0,Many,Many,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,Wind,NaN
63,R26_013,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,14,Quiet,Low,Traffic,Human voices,Wind,Seagulls,3.0,3.0,NaN,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Seaguls,NaN
64,R26_014,9/22/2026,L04 PathFrontiHub,Sunny,18,Loud,Moderate,Traffic,Human voices,Trees,Wind,0.0,3.0,Many,NaN,Many,NaN,Neutral,Easy,Neutral,Less connected,Trees,NaN
65,R26_014,9/22/2026,L05 GreenFrontSportsCentre,Sunny,18,Moderate,Low,Traffic,Human voices,Seagulls,Trees,0.0,0.0,Many,Some,Some,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Uncut Grass,NaN
69,R26_015,9/23/2026,L02 LibraryGreen,Sunny,18,Moderate,Moderate,Traffic,Human voices,Other birds,Wind,0.0,1.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,No change,"Trees, birds, wind sound",gardai
70,R26_015,9/23/2026,L04 PathFrontiHub,Sunny,17,Loud,High,Traffic,Human voices,Wind,Trees,1.0,0.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Trees, bushes",fumes
71,R26_015,9/23/2026,L05 GreenFrontSportsCentre,Sunny,17,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,3.0,Many,Many,Some,NaN,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,NaN
72,R26_015,9/23/2026,L06 HedgingBehindSportsCentre,Sunny,17,Quiet,Low,Human voices,Traffic,Other birds,Trees,0.0,0.0,Many,Many,Many,NaN,Positive wellbeing,Neutral,Very calm,No change,Grass,chair noises in sports hall
73,R26_015,9/23/2026,L07 CarParkNearSportsCentre,Sunny,17,Quiet,Low,Other,Human voices,Wind,Trees,3.0,1.0,Many,Many,Some,Many,Neutral,Easy,Mostly calm,Less connected,"Trees, birds, wind sound",machinery
74,R26_016,9/23/2026,L02 LibraryGreen,Sunny,17,Moderate,High,Traffic,Other,Wind,Insects,0.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,same,Trees and Grass,NaN
75,R26_016,9/23/2026,L04 PathFrontiHub,Sunny,17,Loud,Moderate,Traffic,Human voices,Wind,Wind,0.0,0.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,A little more connected,Trees and Grass,Traffic Volume highest here
76,R26_016,9/23/2026,L05 GreenFrontSportsCentre,Sunny,17,Moderate,Low,Traffic,Human voices,Trees,Insects,2.0,3.0,Many,Many,Some,NaN,Neutral,Easy,Very calm,A little more connected,Trees and Grass,NaN
77,R26_016,9/23/2026,L06 HedgingBehindSportsCentre,Sunny,17,Quiet,Low,Human voices,Other,Trees,Other birds,0.0,0.0,Many,Some,Some,NaN,Positive wellbeing,Easy,Very calm,A little more connected,NaN,NaN
78,R26_016,9/23/2026,L07 CarParkNearSportsCentre,Sunny,17,Quiet,Low,Other,Other,Wind,Wind,3.0,1.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,Less connected,NaN,Teleporter and lots of cars (Parking lot)
79,R26_017,9/23/2026,L01 MainEntrance,Partly cloudy,17,Quiet,Low,Traffic,Human voices,Wind,Other birds,1.0,0.0,Many,Many,Some,NaN,Positive wellbeing,Neutral,Mostly calm,No change,grass,a lot of wasp
80,R26_017,9/23/2026,L02 LibraryGreen,Partly cloudy,17,Loud,High,Traffic,Human voices,Wind,Trees,0.0,0.0,Many,Many,Some,NaN,Neutral,Neutral,Neutral,A little more connected,trees,rocks on the floor
81,R26_017,9/23/2026,L07 CarParkNearSportsCentre,Partly cloudy,17,Quiet,Low,Human voices,Service machinery,Wind,Other,1.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees,a telehandler
82,R26_017,9/23/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17,Quiet,Low,Traffic,Service machinery,Insects,Wind,1.0,0.0,Many,Some,Some,NaN,Low wellbeing,Vey easy,Neutral,Less connected,ornamental plants,NaN
83,R26_017,9/23/2026,L04 PathFrontiHub,Partly cloudy,17,Loud,High,Human voices,Human voices,Wind,Trees,1.0,0.0,Many,Many,Some,NaN,Neutral,Neutral,Neutral,Less connected,Trees and Grass,Berries on the bush
84,R26_018,9/23/2026,L05 GreenFrontSportsCentre,Partly cloudy,17,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,3.0,Many,Many,Some,NaN,Neutral,Neutral,Neutral,A little more connected,Trees,Patio made for sitting and relaxing
85,R26_018,9/23/2026,L06 HedgingBehindSportsCentre,Sunny,16,Quiet,Low,Human voices,Other,Other birds,Trees,1.0,0.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,No change,Spider and Shrubs,NaN
86,R26_018,9/23/2026,L07 CarParkNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Other,Wind,Trees,3.0,1.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Nothing worth noting,Teleporter and lots of cars (Parking lot)
87,R26_018,9/23/2026,L02 LibraryGreen,Partly cloudy,17,Moderate,High,Human voices,Traffic,Other birds,Wind,0.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees and Grass,Lot of people nd olice station
88,R26_018,9/23/2026,L04 PathFrontiHub,Partly cloudy,17,Moderate,Moderate,Human voices,Traffic,Wind,Trees,1.0,0.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,Trees,Traffic Volume highest here
89,R26_019,9/24/2026,L04 PathFrontiHub,Sunny,17,Moderate,High,Traffic,Human voices,Wind,Trees,7.0,6.0,Many,Some,Some,Some,Positive wellbeing,Slighly uneasy,Neutral,A little more connected,Bugs,Lots of smokers/vapers
90,R26_019,9/25/2026,L03 LowerSidePathiHub,Sunny,17,Quiet,Low,Human voices,Traffic,Wind,Trees,1.0,0.0,Many,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Lots of weeds,No one around
91,R26_019,9/26/2026,L05 GreenFrontSportsCentre,Sunny,17,Quiet,Low,Traffic,Human voices,Trees,Wind,3.0,0.0,Many,Some,NaN,NaN,Very positive wellbeing,Vey easy,Very calm,Much more connected,Wild ladybug apppeared on me,Ants on my sheet
92,R26_019,9/27/2026,L06 HedgingBehindSportsCentre,Sunny,17,Quiet,Low,Construction,Human voices,Wind,Trees,2.0,2.0,One or two,Some,Some,Some,Neutral,Slighly uneasy,Neutral,Much more connected,"Crabapple tree, apples sour",Lots of webs no spiders
93,R26_019,9/28/2026,L07 CarParkNearSportsCentre,Sunny,17,Quiet,Low,Construction,Service machinery,Other birds,Seagulls,20.0,1.0,One or two,Some,NaN,NaN,Positive wellbeing,Vey easy,Mostly calm,A little more connected,A wild mushroom appeared,Big tele handler with extended Boom
94,R26_020,9/23/2026,L05 GreenFrontSportsCentre,sunny,17,Quiet,Low,Human voices,NaN,Wind,Trees,1.0,0.0,Many,Many,Many,NaN,Positive wellbeing,Easy,Mostly calm,Much more connected,bit shaded area,trash/cloths near the wall area
95,R26_021,9/24/2026,L03 LowerSidePathiHub,sunny,17,Quiet,Low,Human voices,NaN,Wind,NaN,2.0,0.0,Many,Some,Many,Many,Positive wellbeing,Easy,Mostly calm,Much more connected,quiet almost no people arounf,NaN
96,R26_022,9/25/2026,L06 HedgingBehindSportsCentre,sunny,17,Quiet,Low,Human voices,NaN,Wind,NaN,2.0,3.0,One or two,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,small apple tree,very sour apples growing on the tree advised not to try them
97,R26_023,9/26/2026,L07 CarParkNearSportsCentre,sunny,17,Quiet,Low,Construction,Other,Other birds,Other,25.0,5.0,One or two,Some,Some,NaN,Positive wellbeing,Easy,Mostly calm,Much more connected,clean area,telehandler parked close by eye sore

### Temperature Data Clean

I noticed for the temperature some poeople had put in 'C' after the number for the temperature and some also used decimals.

To solve this I used the function below to replace the C with blankspace and to make all value type a float to accomate the decimals.

In [67]:
df["temperature_c"] = df["temperature_c"].astype(str).str.replace("C", "").astype(float)

display(df[["recorder_id", "temperature_c"]])

    recorder_id  temperature_c
0       R26_001           16.0
1       R26_001           16.0
2       R26_001           16.0
3       R26_001           16.0
4       R26_001           16.0
5       R26_002           17.0
6       R26_002           17.0
7       R26_002           19.0
8       R26_002           16.0
9       R26_002           18.0
10      R26_003           18.0
11      R26_003           17.0
12      R26_003           18.0
13      R26_003           16.0
14      R26_003           18.0
15      R26_004           17.0
16      R26_004           16.0
17      R26_004           17.0
18      R26_004           19.0
19      R26_004           18.0
20      R26_005           16.0
21      R26_005           16.0
22      R26_005           16.0
23      R26_005           15.0
24      R26_005           16.0
25      R26_006           16.0
26      R26_006           16.0
27      R26_006           16.0
28      R26_006           16.0
29      R26_006           16.0
30      R26_007           17.0
31      R26_007           16.0
32      R26_007           17.0
33      R26_007           15.0
34      R26_007           16.0
35      R26_008           16.0
36      R26_008           16.0
37      R26_008           16.0
38      R26_008           16.0
39      R26_008           16.0
40      R26_009           16.0
41      R26_009           16.0
42      R26_009           16.0
43      R26_009           17.0
44      R26_009           15.0
45      R26_010           17.0
46      R26_010           17.0
47      R26_010           17.0
48      R26_010           17.0
49      R26_010           17.0
50      R26_011           17.0
51      R26_011           16.0
52      R26_011           17.0
53      R26_011           17.0
54      R26_011           17.0
55      R26_012           18.0
56      R26_012           17.0
57      R26_012           13.0
58      R26_012           17.0
59      R26_013           16.0
60      R26_013           17.0
61      R26_013           16.5
62      R26_013           18.0
63      R26_013           14.0
64      R26_014           18.0
65      R26_014           18.0
69      R26_015           18.0
70      R26_015           17.0
71      R26_015           17.0
72      R26_015           17.0
73      R26_015           17.0
74      R26_016           17.0
75      R26_016           17.0
76      R26_016           17.0
77      R26_016           17.0
78      R26_016           17.0
79      R26_017           17.0
80      R26_017           17.0
81      R26_017           17.0
82      R26_017           17.0
83      R26_017           17.0
84      R26_018           17.0
85      R26_018           16.0
86      R26_018           16.0
87      R26_018           17.0
88      R26_018           17.0
89      R26_019           17.0
90      R26_019           17.0
91      R26_019           17.0
92      R26_019           17.0
93      R26_019           17.0
94      R26_020           17.0
95      R26_021           17.0
96      R26_022           17.0
97      R26_023           17.0
98      R26_024           17.0
99      R26_021           17.0
100     R26_021           17.0
101     R26_021           17.0
102     R26_021           17.0
103     R26_021           17.0
104     R26_022           17.0
105     R26_022           17.0
106     R26_022           17.0
107     R26_022           17.0
108     R26_022           17.0
109     R26_023           17.0
110     R26_023           17.0
111     R26_023           17.0
112     R26_023           17.0
113     R26_023           17.0
114     R26_024           16.0
115     R26_024           19.0
116     R26_024           19.0
117     R26_024           17.0
118     R26_024           17.0
119     R26_025           17.0
120     R26_025           19.0
121     R26_025           18.0
122     R26_025           16.0
123     R26_025           17.0
124     R26_026           17.0
125     R26_026           17.0
126     R26_026           17.0
127     R26_026           17.0
128     R26_026           17.0
129     R26_027           17.0
130     R26_027           19.0
131     R26_027           18.0
132     R26_027           16.0
133     R26_027           16.0

### Categorical cleaning

In [68]:
# 1. Standardize capitalization inconsistencies
df['weather'] = df['weather'].str.capitalize()
df['foot_traffic'] = df['foot_traffic'].str.capitalize()

# 2. Correct typos in ease_rating
df['ease_rating'] = df['ease_rating'].replace({
    'Vey easy': 'Very easy',
    'Slighly uneasy': 'Slightly uneasy'
})

# 3. Standardize similar ratings
df['nature_connection_experience_rating'] = df['nature_connection_experience_rating'].replace({
    'same': 'No change'
})

# Check the results
for col in ['weather', 'foot_traffic', 'ease_rating', 'nature_connection_experience_rating']:
    print(f"--- Cleaned '{col}' uniqueness ---")
    print(df[col].unique())
    print()

--- Cleaned 'weather' uniqueness ---
['Partly cloudy' 'Sunny' 'Windy' 'Cloudy']

--- Cleaned 'foot_traffic' uniqueness ---
['Low' 'Moderate' 'High']

--- Cleaned 'ease_rating' uniqueness ---
['Neutral' 'Easy' 'Very easy' 'Very uneasy' 'Slightly uneasy']

--- Cleaned 'nature_connection_experience_rating' uniqueness ---
['Less connected' 'A little more connected' 'No change'
 'Much more connected']

### Encoding

#### Data inspection before encoding

In [69]:
categorical_cols = [
    'weather', 'sound level', 'foot_traffic',
    'wellbeing_rating', 'ease_rating', 'stress_rating',
    'nature_connection_experience_rating'
]

for col in categorical_cols:
    if col in df.columns:
        print(f"--- Value counts for '{col}' (Total Nulls: {df[col].isnull().sum()}) ---")
        print(df[col].value_counts(dropna=False))
        print("\n")

--- Value counts for 'weather' (Total Nulls: 0) ---
weather
Sunny            84
Partly cloudy    36
Cloudy            7
Windy             4
Name: count, dtype: int64


--- Value counts for 'sound level' (Total Nulls: 0) ---
sound level
Moderate    58
Quiet       57
Loud        16
Name: count, dtype: int64


--- Value counts for 'foot_traffic' (Total Nulls: 0) ---
foot_traffic
Low         94
Moderate    24
High        13
Name: count, dtype: int64


--- Value counts for 'wellbeing_rating' (Total Nulls: 0) ---
wellbeing_rating
Positive wellbeing         67
Neutral                    37
Very positive wellbeing    18
Low wellbeing               7
Very low wellbeing          2
Name: count, dtype: int64


--- Value counts for 'ease_rating' (Total Nulls: 0) ---
ease_rating
Easy               56
Neutral            36
Very easy          23
Slightly uneasy    15
Very uneasy         1
Name: count, dtype: int64


--- Value counts for 'stress_rating' (Total Nulls: 0) ---
stress_rating
Mostly calm       58
Neutral           37
Very calm         29
Stressful          6
Very stressful     1
Name: count, dtype: int64


--- Value counts for 'nature_connection_experience_rating' (Total Nulls: 0) ---
nature_connection_experience_rating
A little more connected    42
No change                  35
Much more connected        29
Less connected             25
Name: count, dtype: int64

Data encoding

#### Foot Traffic Encoding

In [70]:
foot_traffic_map = {
    'Low': 1,
    'Moderate': 2,
    'High': 3
}

df['foot_traffic_encoded'] = df['foot_traffic'].map(foot_traffic_map)

#### Wellbeing encoding

In [71]:
wellbeing_map = {
    'Very low wellbeing': 1,
    'Low wellbeing': 2,
    'Neutral': 3,
    'Positive wellbeing': 4,
    'Very positive wellbeing': 5
}

df['wellbeing_rating_encoded'] = df['wellbeing_rating'].map(wellbeing_map)

#### Ease encoding

In [72]:
ease_map = {
    'Very uneasy': 1,
    'Slightly uneasy': 2,
    'Neutral': 3,
    'Easy': 4,
    'Very easy': 5
}

df['ease_rating_encoded'] = df['ease_rating'].map(ease_map)

#### Stress encoding

In [73]:
stress_map = {
    'Very calm': 1,
    'Mostly calm': 2,
    'Neutral': 3,
    'Stressful': 4,
    'Very stressful': 5
}

df['stress_rating_encoded'] = df['stress_rating'].map(stress_map)

#### Connection to nature encoding

In [74]:
nature_conn_map = {
    'Less connected': 1,
    'No change': 2,
    'A little more connected': 3,
    'Much more connected': 4
}

df['nature_connection_encoded'] = df['nature_connection_experience_rating'].map(nature_conn_map)

In [77]:
display(df)

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,other_sound_type_nature,insects_count,birds_count,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element,other_notes,foot_traffic_encoded,wellbeing_rating_encoded,ease_rating_encoded,stress_rating_encoded,nature_connection_encoded
0,R26_001,9/22/2026,L01 MainEntrance,Partly cloudy,16.0,Quiet,Low,Human voices,Traffic,Wind,Trees,0.0,1.0,Many,Some,Some,Some,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees,NaN,1,4,3,4,1
1,R26_001,9/22/2026,L02 LibraryGreen,Sunny,16.0,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,2.0,Many,NaN,Some,NaN,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass,NaN,1,4,3,3,3
2,R26_001,9/22/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16.0,Quiet,Low,Construction,Traffic,Wind,Other birds,10.0,20.0,Many,NaN,Many,Some,Positive wellbeing,Easy,Mostly calm,No change,Very quiet,NaN,1,4,4,2,2
3,R26_001,9/22/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16.0,Moderate,Low,Human voices,Human voices,Wind,Other birds,0.0,2.0,One or two,Some,NaN,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind,NaN,1,4,3,3,4
4,R26_001,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,16.0,Moderate,Low,Traffic,Other,Wind,Trees,0.0,0.0,One or two,NaN,Some,NaN,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area,NaN,1,4,4,2,1
5,R26_002,9/22/2026,L01 MainEntrance,Sunny,17.0,Moderate,Low,Traffic,Human voices,Other birds,Insects,2.0,4.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush,1,4,4,2,3
6,R26_002,9/22/2026,L04 PathFrontiHub,Windy,17.0,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Neutral,Neutral,Very calm,No change,plants and trees,NaN,1,3,3,1,2
7,R26_002,9/22/2026,L05 GreenFrontSportsCentre,Sunny,19.0,Moderate,Low,Traffic,Service machinery,Wind,Other,7.0,0.0,Many,Many,Many,Many,Positive wellbeing,Very easy,Mostly calm,Much more connected,wild plants,NaN,1,4,5,2,4
8,R26_002,9/22/2026,L06 HedgingBehindSportsCentre,Cloudy,16.0,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Very calm,Less connected,shaded area,NaN,1,3,3,1,1
9,R26_002,9/22/2026,L07 CarParkNearSportsCentre,Sunny,18.0,Quiet,Low,Service machinery,Traffic,Other birds,Trees,6.0,2.0,Many,Many,Many,Some,Very positive wellbeing,Very easy,Very calm,Much more connected,insects,NaN,1,5,5,1,4
10,R26_003,9/22/2026,L01 MainEntrance,Sunny,18.0,Moderate,Low,Traffic,Human voices,Other birds,Wind,1.0,4.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush,1,4,4,2,3
11,R26_003,9/22/2026,L04 PathFrontiHub,Sunny,17.0,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Easy,Mostly calm,Much more connected,The Plants,NaN,1,5,4,2,4
12,R26_003,9/22/2026,L05 GreenFrontSportsCentre,Sunny,18.0,Moderate,Moderate,Traffic,Service machinery,Wind,Insects,7.0,1.0,Many,Many,Many,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,The Wild Plants,NaN,2,4,4,2,3
13,R26_003,9/22/2026,L06 HedgingBehindSportsCentre,Cloudy,16.0,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,Less connected,Shaded area,NaN,1,3,3,3,1
14,R26_003,9/22/2026,L07 CarParkNearSportsCentre,Sunny,18.0,Quiet,Low,Service machinery,Traffic,Trees,Insects,5.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Very easy,Very calm,Much more connected,Insects,NaN,1,5,5,1,4
15,R26_004,9/22/2026,L04 PathFrontiHub,Sunny,17.0,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Very easy,Very calm,Much more connected,Plants,NaN,1,5,5,1,4
16,R26_004,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,16.0,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,Less connected,Shaded area,NaN,1,3,3,3,1
17,R26_004,9/22/2026,L01 MainEntrance,Sunny,17.0,Moderate,Low,Traffic,Human voices,Other birds,Wind,1.0,4.0,One or two,Some,Some,Many,Very positive wellbeing,Very easy,Very calm,Much more connected,Trees,NaN,1,5,5,1,4
18,R26_004,9/22/2026,L05 GreenFrontSportsCentre,Sunny,19.0,Moderate,Low,Traffic,Human voices,Wind,Insects,1.0,0.0,Many,Many,Many,Many,Very positive wellbeing,Very easy,Very calm,Much more connected,Reddish plants,NaN,1,5,5,1,4
19,R26_004,9/22/2026,L02 LibraryGreen,Sunny,18.0,Quiet,Low,Service machinery,Traffic,Trees,Insects,5.0,2.0,Many,Some,Some,Some,Very positive wellbeing,Very easy,Very calm,Much more connected,Insects,NaN,1,5,5,1,4
20,R26_005,9/22/2026,L01 MainEntrance,Sunny,16.0,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,1.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,The wind,NaN,1,3,3,3,2
21,R26_005,9/22/2026,L02 LibraryGreen,Sunny,16.0,Quiet,Low,Traffic,Human voices,Trees,Insects,1.0,0.0,Many,Some,Many,NaN,Very positive wellbeing,Very easy,Very calm,Much more connected,Leaves falling,NaN,1,5,5,1,4
22,R26_005,9/22/2026,L04 PathFrontiHub,Sunny,16.0,Moderate,Low,Traffic,Human voices,Wind,Other,0.0,3.0,Many,Some,Some,NaN,Very low wellbeing,Very uneasy,Very stressful,No change,Faint music from car,NaN,1,1,1,5,2
23,R26_005,9/22/2026,L05 GreenFrontSportsCentre,Sunny,15.0,Quiet,Low,Other,Human voices,Trees,Other birds,0.0,2.0,Many,Many,Many,Some,Low wellbeing,Very easy,Mostly calm,Much more connected,Quiet,NaN,1,2,5,2,4
24,R26_005,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,16.0,Quiet,Low,Construction,Traffic,Seagulls,Other birds,2.0,4.0,Many,Many,Some,Some,Low wellbeing,Slightly uneasy,Mostly calm,No change,Seaguls,NaN,1,2,2,2,2
25,R26_006,9/22/2026,L01 MainEntrance,Partly cloudy,16.0,Moderate,Moderate,Human voices,Traffic,Wind,Other birds,0.0,0.0,Many,NaN,Some,Some,Low wellbeing,Slightly uneasy,Stressful,Less connected,Trees,NaN,2,2,2,4,1
26,R26_006,9/22/2026,L02 LibraryGreen,Partly cloudy,16.0,Moderate,Low,Traffic,Human voices,Other birds,Wind,5.0,2.0,Many,NaN,NaN,NaN,Neutral,Easy,Neutral,A little more connected,Grass,NaN,1,3,4,3,3
27,R26_006,9/22/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16.0,Quiet,Low,Construction,Traffic,Other birds,Wind,2.0,12.0,One or two,NaN,Some,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Plants,NaN,1,4,3,2,3
28,R26_006,9/22/2026,L07 CarParkNearSportsCentre,Sunny,16.0,Quiet,Low,Construction,Traffic,Wind,Trees,0.0,1.0,One or two,Some,NaN,Some,Very low wellbeing,Slightly uneasy,Stressful,Less connected,lawn,NaN,1,1,2,4,1
29,R26_006,9/22/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16.0,Moderate,Low,Traffic,Other,Wind,Other birds,0.0,0.0,One or two,NaN,Some,Some,Low wellbeing,Neutral,Mostly calm,No change,Tree,Generator,1,2,3,2,2
30,R26_007,9/22/2026,L01 MainEntrance,Partly cloudy,17.0,Moderate,High,Human voices,Traffic,Trees,Other birds,3.0,4.0,Many,Some,Many,Some,Neutral,Slightly uneasy,Stressful,No change,Wind,NaN,3,3,2,4,2
31,R26_007,9/22/2026,L03 LowerSidePathiHub,Cloudy,16.0,Moderate,Low,Traffic,Human voices,Other birds,Insects,3.0,1.0,One or two,Some,NaN,Many,Positive wellbeing,Neutral,Mostly calm,No change,NaN,Trash,1,4,3,2,2
32,R26_007,9/22/2026,L04 PathFrontiHub,Sunny,17.0,Loud,Moderate,Traffic,Human voices,Other birds,Wind,3.0,1.0,One or two,Some,Some,Some,Neutral,Slightly uneasy,Mostly calm,No change,Wind,Ambulance,2,3,2,2,2
33,R26_007,9/22/2026,L06 HedgingBehindSportsCentre,Cloudy,15.0,Quiet,Moderate,Traffic,Construction,Trees,Other birds,31.0,12.0,Many,Some,Many,Many,Positive wellbeing,Easy,Mostly calm,No change,Snails on wall,NaN,2,4,4,2,2
34,R26_007,9/22/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16.0,Quiet,Low,Traffic,Other,Wind,Other birds,4.0,1.0,One or two,Some,Some,Many,Neutral,Slightly uneasy,Neutral,No change,Tweeting Birds,NaN,1,3,2,3,2
35,R26_008,22/09/2026,L01 MainEntrance,Partly cloudy,16.0,Moderate,Moderate,Human voices,Traffic,Wind,Wind,1.0,3.0,Many,Some,NaN,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Sunny,NaN,2,4,3,2,3
36,R26_008,22/09/2026,L03 LowerSidePathiHub,Partly cloudy,16.0,Moderate,Low,Traffic,Traffic,Trees,Wind,0.0,3.0,Many,Many,NaN,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,Quiet,NaN,1,4,4,2,3
37,R26_008,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16.0,Quiet,Low,Service machinery,Traffic,Wind,Other birds,3.0,3.0,One or two,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,NaN,1,4,4,2,3
38,R26_008,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16.0,Quiet,Low,Human voices,Human voices,Wind,Trees,26.0,13.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,A soft yellow golf ball,1,4,4,2,3
39,R26_008,22/09/2026,L04 PathFrontiHub,Partly cloudy,16.0,Moderate,Moderate,Traffic,Other,Wind,Wind,1.0,3.0,Many,Some,Some,NaN,Positive wellbeing,Easy,Mostly calm,A little more connected,NaN,NaN,2,4,4,2,3
40,R26_009,9/22/2026,L01 MainEntrance,Sunny,16.0,Moderate,Moderate,Human voices,Traffic,Trees,Other birds,1.0,3.0,Many,Some,Many,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Barren,People smoking,2,4,3,2,3
41,R26_009,9/22/2026,L02 LibraryGreen,Sunny,16.0,Moderate,Low,Traffic,Human voices,Wind,Trees,1.0,1.0,Many,Many,Some,Many,Very positive wellbeing,Easy,Very calm,Much more connected,Fallen leaves,Bags left outside library wall,1,5,4,1,4
42,R26_009,9/22/2026,L04 PathFrontiHub,Sunny,16.0,Loud,Low,Traffic,Human voices,Wind,Trees,0.0,1.0,Many,Some,Many,Many,Neutral,Slightly uneasy,Stressful,Less connected,More variety in planted shrubs,Loud traffic noise,1,3,2,4,1
43,R26_009,9/22/2026,L05 GreenFrontSportsCentre,Sunny,17.0,Quiet,Low,Traffic,Human voices,Wind,Trees,5.0,0.0,Many,Many,Many,Many,Very positive wellbeing,Easy,Mostly calm,Much more connected,Little annoying bugs,Lots of dumped clothes,1,5,4,2,4
44,R26_009,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,15.0,Quiet,Low,Traffic,Construction,Trees,Seagulls,6.0,1.0,NaN,Some,Some,Many,Neutral,Neutral,Very calm,Much more connected,Lots of bushes,Yellow Golfball,1,3,3,1,4
45,R26_010,9/22/2026,L01 MainEntrance,Partly cloudy,17.0,Moderate,Low,Human voices,Traffic,Wind,Other birds,1.0,0.0,Many,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Smoking people,NaN,1,4,4,2,3
46,R26_010,9/22/2026,L02 LibraryGreen,Partly cloudy,17.0,Loud,Moderate,Traffic,Human voices,Wind,Wind,0.0,2.0,Many,Some,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,More birds,NaN,2,4,4,2,3
47,R26_010,9/22/2026,L04 PathFrontiHub,Partly cloudy,17.0,Loud,Low,Traffic,Human voices,Wind,Insects,1.0,0.0,Many,Some,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Spider,NaN,1,4,4,2,3
48,R26_010,9/22/2026,L05 GreenFrontSportsCentre,Partly cloudy,17.0,Moderate,Low,Traffic,Traffic,Wind,Wind,0.0,0.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Trafic sound,NaN,1,4,4,2,3
49,R26_010,9/22/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17.0,Quiet,Low,Traffic,Traffic,Wind,Wind,0.0,0.0,NaN,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,crab apple,NaN,1,4,4,2,3
50,R26_011,9/22/2026,L01 MainEntrance,Partly cloudy,17.0,Loud,High,Human voices,Traffic,Wind,Other birds,1.0,2.0,Many,Many,NaN,Some,Positive wellbeing,Easy,Very calm,No change,Trees,Smoking,3,4,4,1,2
51,R26_011,9/22/2026,L02 LibraryGreen,Partly cloudy,16.0,Loud,Moderate,Traffic,Human voices,Other birds,Trees,4.0,2.0,Many,Some,NaN,Some,Positive wellbeing,Easy,Mostly calm,Less connected,Grass,NaN,2,4,4,2,1
52,R26_011,9/22/2026,L03 LowerSidePathiHub,Partly cloudy,17.0,Quiet,Low,Human voices,Traffic,Seagulls,Wind,0.0,2.0,One or two,Some,Many,Some,Positive wellbeing,Easy,Very calm,No change,Flowerbed,NaN,1,4,4,1,2
53,R26_011,9/22/2026,L05 GreenFrontSportsCentre,Partly cloudy,17.0,Moderate,Low,Traffic,Human voices,Trees,Wind,3.0,1.0,Many,Many,Some,NaN,Positive wellbeing,Easy,Very calm,No change,Wildflower area,pathway,1,4,4,1,2
54,R26_011,9/22/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17.0,Quiet,Low,Other,Human voices,Other birds,Trees,1.0,2.0,Many,Some,Many,NaN,Positive wellbeing,Easy,Very calm,No change,Bush,gunshots,1,4,4,1,2
55,R26_012,9/22/2026,L05 GreenFrontSportsCentre,Sunny,18.0,Moderate,Low,Traffic,Other,Other,Wind,20.0,0.0,Many,Many,NaN,Some,Neutral,Neutral,Neutral,Less connected,some sort of a falcon,NaN,1,3,3,3,1
56,R26_012,9/22/2026,L02 LibraryGreen,Sunny,17.0,Loud,Moderate,Traffic,Human voices,Other birds,Other birds,0.0,10.0,Many,NaN,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Birds, Trees",Construction site,2,4,4,2,2
57,R26_012,9/22/2026,L06 HedgingBehindSportsCentre,Cloudy,13.0,Quiet,Low,Construction,Traffic,Other birds,Trees,10.0,5.0,Many,Some,NaN,NaN,Very positive wellbeing,Very easy,Very calm,No change,"Trees, bushes",People,1,5,5,1,2
58,R26_012,9/22/2026,L01 MainEntrance,Sunny,17.0,Loud,High,Human voices,Traffic,Other birds,Wind,0.0,5.0,Many,NaN,Some,Many,Very positive wellbeing,Very easy,Mostly calm,No change,"Trees, birds, wind sound",People smoking,3,5,5,2,2
59,R26_013,9/22/2026,L01 MainEntrance,Sunny,16.0,Moderate,High,Human voices,Traffic,Wind,Trees,0.0,3.0,Many,Some,NaN,NaN,Positive wellbeing,Neutral,Very calm,No change,Leaves,NaN,3,4,3,1,2
60,R26_013,9/22/2026,L02 LibraryGreen,Sunny,17.0,Quiet,Low,Traffic,Human voices,Wind,Trees,1.0,0.0,Many,Many,Some,Many,Positive wellbeing,Very easy,Very calm,Much more connected,Moss,NaN,1,4,5,1,4
61,R26_013,9/22/2026,L04 PathFrontiHub,Sunny,16.5,Moderate,Low,Traffic,Human voices,Wind,Other birds,1.0,1.0,Many,Some,Some,Many,Positive wellbeing,Slightly uneasy,Stressful,Less connected,Wind,NaN,1,4,2,4,1
62,R26_013,9/22/2026,L05 GreenFrontSportsCentre,Sunny,18.0,Quiet,Low,Traffic,Human voices,Wind,Other birds,1.0,2.0,Many,Many,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,Wind,NaN,1,4,4,2,3
63,R26_013,9/22/2026,L06 HedgingBehindSportsCentre,Sunny,14.0,Quiet,Low,Traffic,Human voices,Wind,Seagulls,3.0,3.0,NaN,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Seaguls,NaN,1,4,4,3,3
64,R26_014,9/22/2026,L04 PathFrontiHub,Sunny,18.0,Loud,Moderate,Traffic,Human voices,Trees,Wind,0.0,3.0,Many,NaN,Many,NaN,Neutral,Easy,Neutral,Less connected,Trees,NaN,2,3,4,3,1
65,R26_014,9/22/2026,L05 GreenFrontSportsCentre,Sunny,18.0,Moderate,Low,Traffic,Human voices,Seagulls,Trees,0.0,0.0,Many,Some,Some,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Uncut Grass,NaN,1,4,3,3,4
69,R26_015,9/23/2026,L02 LibraryGreen,Sunny,18.0,Moderate,Moderate,Traffic,Human voices,Other birds,Wind,0.0,1.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,No change,"Trees, birds, wind sound",gardai,2,4,4,2,2
70,R26_015,9/23/2026,L04 PathFrontiHub,Sunny,17.0,Loud,High,Traffic,Human voices,Wind,Trees,1.0,0.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Trees, bushes",fumes,3,4,4,2,2
71,R26_015,9/23/2026,L05 GreenFrontSportsCentre,Sunny,17.0,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,3.0,Many,Many,Some,NaN,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,NaN,1,4,4,2,3
72,R26_015,9/23/2026,L06 HedgingBehindSportsCentre,Sunny,17.0,Quiet,Low,Human voices,Traffic,Other birds,Trees,0.0,0.0,Many,Many,Many,NaN,Positive wellbeing,Neutral,Very calm,No change,Grass,chair noises in sports hall,1,4,3,1,2
73,R26_015,9/23/2026,L07 CarParkNearSportsCentre,Sunny,17.0,Quiet,Low,Other,Human voices,Wind,Trees,3.0,1.0,Many,Many,Some,Many,Neutral,Easy,Mostly calm,Less connected,"Trees, birds, wind sound",machinery,1,3,4,2,1
74,R26_016,9/23/2026,L02 LibraryGreen,Sunny,17.0,Moderate,High,Traffic,Other,Wind,Insects,0.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees and Grass,NaN,3,3,3,3,2
75,R26_016,9/23/2026,L04 PathFrontiHub,Sunny,17.0,Loud,Moderate,Traffic,Human voices,Wind,Wind,0.0,0.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,A little more connected,Trees and Grass,Traffic Volume highest here,2,3,3,3,3
76,R26_016,9/23/2026,L05 GreenFrontSportsCentre,Sunny,17.0,Moderate,Low,Traffic,Human voices,Trees,Insects,2.0,3.0,Many,Many,Some,NaN,Neutral,Easy,Very calm,A little more connected,Trees and Grass,NaN,1,3,4,1,3
77,R26_016,9/23/2026,L06 HedgingBehindSportsCentre,Sunny,17.0,Quiet,Low,Human voices,Other,Trees,Other birds,0.0,0.0,Many,Some,Some,NaN,Positive wellbeing,Easy,Very calm,A little more connected,NaN,NaN,1,4,4,1,3
78,R26_016,9/23/2026,L07 CarParkNearSportsCentre,Sunny,17.0,Quiet,Low,Other,Other,Wind,Wind,3.0,1.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,Less connected,NaN,Teleporter and lots of cars (Parking lot),1,3,3,3,1
79,R26_017,9/23/2026,L01 MainEntrance,Partly cloudy,17.0,Quiet,Low,Traffic,Human voices,Wind,Other birds,1.0,0.0,Many,Many,Some,NaN,Positive wellbeing,Neutral,Mostly calm,No change,grass,a lot of wasp,1,4,3,2,2
80,R26_017,9/23/2026,L02 LibraryGreen,Partly cloudy,17.0,Loud,High,Traffic,Human voices,Wind,Trees,0.0,0.0,Many,Many,Some,NaN,Neutral,Neutral,Neutral,A little more connected,trees,rocks on the floor,3,3,3,3,3
81,R26_017,9/23/2026,L07 CarParkNearSportsCentre,Partly cloudy,17.0,Quiet,Low,Human voices,Service machinery,Wind,Other,1.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees,a telehandler,1,3,3,3,2
82,R26_017,9/23/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17.0,Quiet,Low,Traffic,Service machinery,Insects,Wind,1.0,0.0,Many,Some,Some,NaN,Low wellbeing,Very easy,Neutral,Less connected,ornamental plants,NaN,1,2,5,3,1
83,R26_017,9/23/2026,L04 PathFrontiHub,Partly cloudy,17.0,Loud,High,Human voices,Human voices,Wind,Trees,1.0,0.0,Many,Many,Some,NaN,Neutral,Neutral,Neutral,Less connected,Trees and Grass,Berries on the bush,3,3,3,3,1
84,R26_018,9/23/2026,L05 GreenFrontSportsCentre,Partly cloudy,17.0,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,3.0,Many,Many,Some,NaN,Neutral,Neutral,Neutral,A little more connected,Trees,Patio made for sitting and relaxing,1,3,3,3,3
85,R26_018,9/23/2026,L06 HedgingBehindSportsCentre,Sunny,16.0,Quiet,Low,Human voices,Other,Other birds,Trees,1.0,0.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,No change,Spider and Shrubs,NaN,1,3,3,3,2
86,R26_018,9/23/2026,L07 CarParkNearSportsCentre,Partly cloudy,16.0,Moderate,Low,Human voices,Other,Wind,Trees,3.0,1.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Nothing worth noting,Teleporter and lots of cars (Parking lot),1,3,3,3,2
87,R26_018,9/23/2026,L02 LibraryGreen,Partly cloudy,17.0,Moderate,High,Human voices,Traffic,Other birds,Wind,0.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees and Grass,Lot of people nd olice station,3,3,3,3,2
88,R26_018,9/23/2026,L04 PathFrontiHub,Partly cloudy,17.0,Moderate,Moderate,Human voices,Traffic,Wind,Trees,1.0,0.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,Trees,Traffic Volume highest here,2,3,3,3,2
89,R26_019,9/24/2026,L04 PathFrontiHub,Sunny,17.0,Moderate,High,Traffic,Human voices,Wind,Trees,7.0,6.0,Many,Some,Some,Some,Positive wellbeing,Slightly uneasy,Neutral,A little more connected,Bugs,Lots of smokers/vapers,3,4,2,3,3
90,R26_019,9/25/2026,L03 LowerSidePathiHub,Sunny,17.0,Quiet,Low,Human voices,Traffic,Wind,Trees,1.0,0.0,Many,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Lots of weeds,No one around,1,4,4,3,3
91,R26_019,9/26/2026,L05 GreenFrontSportsCentre,Sunny,17.0,Quiet,Low,Traffic,Human voices,Trees,Wind,3.0,0.0,Many,Some,NaN,NaN,Very positive wellbeing,Very easy,Very calm,Much more connected,Wild ladybug apppeared on me,Ants on my sheet,1,5,5,1,4
92,R26_019,9/27/2026,L06 HedgingBehindSportsCentre,Sunny,17.0,Quiet,Low,Construction,Human voices,Wind,Trees,2.0,2.0,One or two,Some,Some,Some,Neutral,Slightly uneasy,Neutral,Much more connected,"Crabapple tree, apples sour",Lots of webs no spiders,1,3,2,3,4

## Data Analysis